# Generated by Django 4.0.3 on 2022-03-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_remove_kategoria_opis_alter_kategoria_nazwa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkty',
            old_name='CENA',
            new_name='cena',
        ),
    ]
